services:
  beentheredonethat:
    image: ghcr.io/kj7ppk/been-there-done-that:latest
    container_name: beentheredonethat
    ports:
      - "8016:8000"
    volumes:
      - ./data:/app/data
    environment:
      - APP_USER=Whomever
      - TZ=America/Los_Angeles
    restart: unless-stopped
