version: "3"
services:
  beentheredonethat:
    build: .
    ports:
      - "8016:8000"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=America/Los_Angeles
    restart: unless-stopped